media_directory.settings:
  type: config_object
  mapping:
    media_directory_vocabulary_mapping:
      label: Vocabulary to use, per media type
      type: sequence
      sequence:
        type: string
